### PR TITLE
I finished 4 tasks and want to finish task 5 during the interview bec…

### PR DESCRIPTION
**Pull request by Shakhzod-d**
…ause I have extra questions

### CODE REVIEW

**Comment by bringmetheaugust** [comment]
@Shakhzod-d , You can ask Your extra question here and complete that task by Yourself

**Comment by Shakhzod-d** [comment]
It is asked to optimize the code, so do you want me to create one component
and map an array that has 3 elements?, so now instead of using 3 components
do I need to create one component and use it 3 times ? One component will
be common? Do you want me to do like this ? Would you please give me some
note what give me instructions for this? Thank you a lot

**Comment by bringmetheaugust** [comment]
@Shakhzod-d, actually creating one universal component is a bad idea.
Let's imagine You have 100 similar components that are somewhat **similar to each other**. What would you do?)
This is the essence of the task so that the candidate comes up with a universal solution.

**Comment by Shakhzod-d** [comment]
I see, I did like this and I hope so it is ok, if not then let me google
it, https://github.com/bringmetheaugust/welcome_to_TE/pull/4

**Pull request closed without merging**
